version: '3.7'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '4000:80'
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
